sonar.projectKey=nl.clockwork.ebms
sonar.projectName=EbMS
sonar.sources=ebms-admin/src/main/java,ebms-core/common/src/main/java,ebms-core/core/src/main/java,ebms-core/plugin/cache/ehcache/src/main/java,ebms-core/plugin/cache/hazelcast/src/main/java,ebms-core/plugin/db/db2/src/main/java,ebms-core/plugin/db/h2/src/main/java,ebms-core/plugin/db/hsqldb/src/main/java,ebms-core/plugin/db/mariadb/src/main/java,ebms-core/plugin/db/mssql/src/main/java,ebms-core/plugin/db/oracle/src/main/java,ebms-core/plugin/db/postgres/src/main/java
sonar.exclusions=ebms-core/core/src/main/java/org/oasis_open/**,ebms-core/core/src/main/java/org/w3/**,ebms-core/core/src/main/java/org/xmlsoap/**,ebms-admin/src/main/java/nl/clockwork/ebms/querydsl/model/Q*.java
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6,e7
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S106
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e2.ruleKey=java:S107
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e3.ruleKey=java:S110
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e4.ruleKey=java:S125
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e5.ruleKey=java:S1134
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e6.ruleKey=java:S1135
sonar.issue.ignore.multicriteria.e6.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.e7.ruleKey=java:S1192
sonar.issue.ignore.multicriteria.e7.resourceKey=**/*.java
sonar.java.source=17
sonar.java.binaries=ebms-admin/target/classes,ebms-core/common/target/classes,ebms-core/core/target/classes,ebms-core/plugin/cache/ehcache/target/classes,ebms-core/plugin/cache/hazelcast/target/classes,ebms-core/plugin/db/db2/target/classes,ebms-core/plugin/db/h2/target/classes,ebms-core/plugin/db/hsqldb/target/classes,ebms-core/plugin/db/mariadb/target/classes,ebms-core/plugin/db/mssql/target/classes,ebms-core/plugin/db/oracle/target/classes,ebms-core/plugin/db/postgres/target/classes
